name: task3-prod

services:
# ************************** Web app
  web-app:
    image: myregistry.com/myapp:1.0.1 
    container_name: src
    volumes:
      - web_root:/var/www/html

# ************************** PHP-FPM service
  php-fpm:
    image: php-fpm:latest
    container_name: php_fpm
    # Volumes
    volumes:
      - web_root:/var/www/html    
    # Resource limits
    cpus: "1.0"
    mem_limit: "256M"
    shm_size: "256M"
    # Healtcheck and restart policy
    healthcheck:
      test: ["CMD", "SCRIPT_NAME=/ping", "SCRIPT_FILENAME=/ping", 
            "REQUEST_METHOD=GET", "cgi-fcgi", "-bind", "-connect", 
            "127.0.0.1:9000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure

    depends_on:
      - web-app
    networks:
      - app-network

# ************************ Nginx server
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app-network
    # Volumes
    volumes:
      - web_root:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
    # Resource limits
    cpus: "0.5"
    mem_limit: "256M"
    shm_size: "256M"

    # Healtcheck and restart policy 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping.php"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure

    depends_on:
      - web-app
      - php-fpm

# ************************** Network 
networks:
  app-network:
    driver: bridge

# *************************** Volumes
volumes:
  web_root:    